.PHONY: clean All

All:
	@echo "----------Building project:[ ass0ciative_container - Debug ]----------"
	@cd "ass0ciative_container" && "$(MAKE)" -f  "ass0ciative_container.mk"
clean:
	@echo "----------Cleaning project:[ ass0ciative_container - Debug ]----------"
	@cd "ass0ciative_container" && "$(MAKE)" -f  "ass0ciative_container.mk" clean
