.PHONY: clean All

All:
	@echo "----------Building project:[ vector - Debug ]----------"
	@cd "vector\vector" && "$(MAKE)" -f  "vector.mk"
clean:
	@echo "----------Cleaning project:[ vector - Debug ]----------"
	@cd "vector\vector" && "$(MAKE)" -f  "vector.mk" clean
